// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg8cn1ic_3Pah1sBudP-nopv1nBF54nag',
    appId: '1:974893836692:web:f70a3588962757f21f0781',
    messagingSenderId: '974893836692',
    projectId: 'staff-app-e7e61',
    authDomain: 'staff-app-e7e61.firebaseapp.com',
    storageBucket: 'staff-app-e7e61.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmKkLDrRpEieE3wLkVq6wN_04VrdZ7Lt8',
    appId: '1:974893836692:android:61c05eaef996b7c61f0781',
    messagingSenderId: '974893836692',
    projectId: 'staff-app-e7e61',
    storageBucket: 'staff-app-e7e61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATzW49kV_8r183VVUnbH7F8QoEOyEBVT0',
    appId: '1:974893836692:ios:7c14c3a61648e1461f0781',
    messagingSenderId: '974893836692',
    projectId: 'staff-app-e7e61',
    storageBucket: 'staff-app-e7e61.appspot.com',
    iosClientId: '974893836692-koqm3e7vneptc2nnfnkud1m0k1iv7sbt.apps.googleusercontent.com',
    iosBundleId: 'com.example.staffApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATzW49kV_8r183VVUnbH7F8QoEOyEBVT0',
    appId: '1:974893836692:ios:7c14c3a61648e1461f0781',
    messagingSenderId: '974893836692',
    projectId: 'staff-app-e7e61',
    storageBucket: 'staff-app-e7e61.appspot.com',
    iosClientId: '974893836692-koqm3e7vneptc2nnfnkud1m0k1iv7sbt.apps.googleusercontent.com',
    iosBundleId: 'com.example.staffApp',
  );
}
